name: macOS build

on:
  pull_request:
  push:
    paths-ignore:
      - '.github/workflows/coverage.yml'
      - '.github/workflows/linux-build.yml'
      - '.github/workflows/msys2-build.yml'
      - '.github/workflows/wasm-build.yml'
      - '.github/workflows/windows-build.yml'
      - '.gitignore'
      - 'LICENSE'
      - 'CHANGELOG.md'
      - 'README.md'
      - 'README_en.md'
      - 'README_fr.md'

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        os: [macOS-latest]
        arch: [x86_64]
        kind: [shared, static]
        confs:
        - { mode: debug, archive: yes }
        - { mode: debug, config: --asan=y, archive: false, cache_key: -asan }
        - { mode: debug, config: --tsan=y, archive: false }
        - { mode: releasedbg, archive: yes }

    runs-on: ${{ matrix.os }}
    if: ${{ !contains(github.event.head_commit.message, 'ci skip') }}

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    # Install xmake
    - name: Setup xmake
      uses: xmake-io/github-action-setup-xmake@v1
      with:
        xmake-version: branch@dev
        actions-cache-folder: .xmake-cache
        package-cache: true
        package-cache-key: ${{ matrix.arch }}-${{ matrix.confs.mode }}${{ matrix.confs.cache_key }}
        build-cache: true
        build-cache-key: ${{ matrix.arch }}-${{ matrix.confs.mode }}${{ matrix.confs.cache_key }}

    # Setup compilation mode and install project dependencies
    - name: Configure xmake and install dependencies
      run: xmake config --arch=${{ matrix.arch }} --mode=${{ matrix.confs.mode }} --static=${{ matrix.kind == 'static' && 'yes' || 'no' }} ${{ matrix.confs.config }} --ccache=n --ffmpeg=y --shadernodes=y --tests=y --unitybuild=y --yes

    # Cache assets downloading
    - name: Restore cached assets
      id: restore-assets
      uses: actions/cache/restore@v4
      with:
        path: assets
        key: assets-${{ hashFiles('assets/examples_version.txt', 'assets/unittests_version.txt') }}

    # Build the engine
    - name: Build Nazara
      run: xmake --yes

    - name: Save downloaded assets
      if: ${{ !steps.restore-assets.outputs.cache-hit }}
      uses: actions/cache/save@v4
      with:
        path: assets
        key: ${{ steps.restore-assets.outputs.cache-primary-key }}

    # Run unit tests
    - name: Run unit tests
      if: matrix.confs.mode != 'releasedbg'
      run: xmake run UnitTests

    # Install the result files
    - name: Install Nazara
      if: ${{ (github.ref == 'refs/heads/main') && github.event_name == 'push' && matrix.confs.archive }}
      run: xmake install -vo package

    - name: "Set PACKAGE_NAME variable"
      if: ${{ (github.ref == 'refs/heads/main') && github.event_name == 'push' && matrix.confs.archive }}
      run: echo "PACKAGE_NAME=macOS_${{ matrix.arch }}_${{ matrix.confs.mode }}_${{ matrix.kind }}.tar.gz" >> $GITHUB_ENV
      shell: bash

    - name: Archive result
      uses: ihiroky/archive-action@v1
      if: ${{ (github.ref == 'refs/heads/main') && github.event_name == 'push' && matrix.confs.archive }}
      with:
        root_dir: package
        file_path: ${{ env.PACKAGE_NAME }}
        verbose: true

    # Nightly tags (for commits to main branch)
    - name: Upload binaries to release (main)
      uses: svenstaro/upload-release-action@v2
      if: ${{ (github.ref == 'refs/heads/main') && github.event_name == 'push' && matrix.confs.archive }}
      with:
        repo_token: ${{ secrets.GITHUB_TOKEN }}
        file: ${{ env.PACKAGE_NAME }}
        asset_name: ${{ env.PACKAGE_NAME }}
        tag: "0.0.0-nightly"
        overwrite: true
